### ISSUE TITLE
'--dns' is not a valid domain for parameter '--domain'

### ISSUE THREAD

**Issue by ppllpig** [ngc7331/docker-derper#1]
'--dns' is not a valid domain for parameter '--domain'
docker shows this,what wrong?

**Comment by ppllpig** [comment]
done.
usage example is wrong.
derp_ not derper_

**Comment by ngc7331** [comment]
Sorry for the mistake, and thanks for pointing that out. README.md is now updated.

Will consider adding a check for environment variables later to provide clearer error logs.
